return function(palette)
  return {
    ["@lsp.type.boolean"] = "@boolean",
    ["@lsp.type.builtinType"] = "@type.builtin",
    ["@lsp.type.comment"] = "@comment",
    ["@lsp.type.decorator"] = "@attribute",
    ["@lsp.type.deriveHelper"] = "@attribute",
    ["@lsp.type.enum"] = "@type",
    ["@lsp.type.enumMember"] = "@constant",
    ["@lsp.type.escapeSequence"] = "@string.escape",
    ["@lsp.type.function"] = "@functionr",
    ["@lsp.type.formatSpecifier"] = "@markup.list",
    ["@lsp.type.generic"] = "@variable",
    ["@lsp.type.interface"] = { fg = palette.teal },
    ["@lsp.type.keyword"] = "@keyword",
    ["@lsp.type.lifetime"] = "@keyword.storage",
    ["@lsp.type.namespace"] = "@module",
    ["@lsp.type.namespace.python"] = "@variable",
    ["@lsp.type.number"] = "@number",
    ["@lsp.type.operator"] = "@operator",
    ["@lsp.type.parameter"] = "@variable.parameter",
    ["@lsp.type.parameter.typescriptreact"] = "@variable",
    ["@lsp.type.property"] = "@property",
    ["@lsp.type.selfKeyword"] = "@variable.builtin",
    ["@lsp.type.selfTypeKeyword"] = "@variable.builtin",
    ["@lsp.type.string"] = "@string",
    ["@lsp.type.typeAlias"] = "@type.definition",
    ["@lsp.type.unresolvedReference"] = { undercurl = true, sp = palette.red },
    ["@lsp.type.variable"] = {}, -- use treesitter
    ["@lsp.typemod.class.defaultLibrary"] = "@function.call",
    ["@lsp.typemod.enum.defaultLibrary"] = "@type.builtin",
    ["@lsp.typemod.enumMember.defaultLibrary"] = "@constant.builtin",
    ["@lsp.typemod.function.defaultLibrary"] = "@function.builtin",
    ["@lsp.typemod.keyword.async"] = "@keyword.coroutine",
    ["@lsp.typemod.keyword.injected"] = "@keyword",
    ["@lsp.typemod.macro.defaultLibrary"] = "@function.builtin",
    ["@lsp.typemod.method.defaultLibrary"] = "@function.method",
    ["@lsp.typemod.operator.injected"] = "@operator",
    ["@lsp.typemod.parameter"] = "@variable.parameter",
    ["@lsp.typemod.string.injected"] = "@string",
    ["@lsp.typemod.struct.defaultLibrary"] = "@type.builtin",
    ["@lsp.typemod.type.defaultLibrary"] = { fg = palette.blue },
    ["@lsp.typemod.typeAlias.defaultLibrary"] = { fg = palette.blue },
    ["@lsp.typemod.variable.callable"] = "@function",
    ["@lsp.typemod.variable.declaration"] = "@constant",
    ["@lsp.typemod.variable.defaultLibrary"] = {},
    ["@lsp.typemod.variable.injected"] = "@variable",
    ["@lsp.typemod.variable.local"] = {},
    ["@lsp.typemod.variable.readonly"] = {},
    ["@lsp.typemod.variable.static"] = "@constant",
  }
end
