return function(palette)
  return {
    ["@annotation"] = "PreProc",
    ["@attribute"] = "PreProc",
    ["@boolean"] = "Boolean",
    ["@character"] = "Character",
    ["@character.printf"] = "SpecialChar",
    ["@character.special"] = "SpecialChar",
    ["@comment"] = "Comment",
    ["@comment.error"] = { fg = palette.red },
    ["@comment.hint"] = { fg = palette.teal },
    ["@comment.info"] = { fg = palette.blue },
    ["@comment.note"] = { fg = palette.teal },
    ["@comment.todo"] = { fg = palette.yellow },
    ["@comment.warning"] = { fg = palette.yellow },
    ["@constant"] = "Constant",
    ["@constant.builtin"] = "Special",
    ["@constant.macro"] = "Define",
    ["@constructor"] = { fg = palette.red },
    ["@constructor.tsx"] = { fg = palette.blue },
    ["@diff.delta"] = "DiffChange",
    ["@diff.minus"] = "DiffDelete",
    ["@diff.plus"] = "DiffAdd",
    ["@function"] = "Function",
    ["@function.builtin"] = "Special",
    ["@function.call"] = "Function",
    ["@function.macro"] = "Macro",
    ["@function.method"] = "Function",
    ["@function.method.call"] = "@function.method",
    ["@keyword"] = "Keyword",
    ["@keyword.conditional"] = "Conditional",
    ["@keyword.coroutine"] = "Keyword",
    ["@keyword.debug"] = "Debug",
    ["@keyword.directive"] = "PreProc",
    ["@keyword.directive.define"] = "Define",
    ["@keyword.exception"] = "Exception",
    ["@keyword.function"] = { fg = palette.red },
    ["@keyword.import"] = "Include",
    ["@keyword.modifier"] = { fg = palette.blue },
    ["@keyword.operator"] = "@operator",
    ["@keyword.repeat"] = "Repeat",
    ["@keyword.return"] = { fg = palette.magenta },
    ["@keyword.storage"] = "StorageClass",
    ["@keyword.type"] = { fg = palette.red },
    ["@label"] = { fg = palette.blue },
    ["@markup"] = "@none",
    ["@markup.emphasis"] = { italic = true },
    ["@markup.environment"] = "Macro",
    ["@markup.environment.name"] = "Type",
    ["@markup.heading"] = "Title",
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = palette.teal },
    ["@markup.link.label"] = "SpecialChar",
    ["@markup.link.label.symbol"] = "Identifier",
    ["@markup.link.url"] = "Underlined",
    ["@markup.list"] = { fg = palette.blue5 },
    ["@markup.list.checked"] = { fg = palette.green },
    ["@markup.list.markdown"] = { fg = palette.orange, bold = true },
    ["@markup.list.unchecked"] = { fg = palette.blue },
    ["@markup.math"] = "Special",
    ["@markup.raw"] = "String",
    ["@markup.raw.markdown_inline"] = "String",
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    ["@module"] = "Type",
    ["@module.builtin"] = { fg = palette.red },
    ["@namespace.builtin"] = "@variable.builtin",
    ["@none"] = {},
    ["@number"] = "Number",
    ["@number.float"] = "Float",
    ["@operator"] = { fg = palette.blue },
    ["@property"] = {},
    ["@punctuation.bracket"] = { fg = palette.teal },
    ["@punctuation.delimiter"] = { fg = palette.blue5 },
    ["@punctuation.special"] = { fg = palette.blue5 },
    ["@punctuation.special.markdown"] = { fg = palette.magenta },
    ["@string"] = "String",
    ["@string.documentation"] = { fg = palette.yellow },
    ["@string.escape"] = { fg = palette.magenta },
    ["@string.regexp"] = { fg = palette.blue5 },
    ["@tag"] = "Label",
    ["@tag.tsx"] = { fg = palette.green },
    ["@tag.attribute"] = "String",
    ["@tag.builtin"] = { fg = palette.green },
    ["@tag.delimiter"] = "Delimiter",
    ["@tag.delimiter.tsx"] = { fg = palette.blue },
    ["@tag.javascript"] = { fg = palette.red },
    ["@type"] = "Type",
    ["@type.builtin"] = { fg = palette.red },
    ["@type.definition"] = "Typedef",
    ["@type.qualifier"] = "@keyword",
    ["@variable"] = { fg = palette.fg },
    ["@variable.builtin"] = { fg = palette.blue5 },
    ["@variable.member"] = {},
    ["@variable.parameter"] = { fg = palette.yellow },
  }
end
