return function(palette)
  return {
    BlinkCmpMenu = { link = "Pmenu" },
    BlinkCmpMenuBorder = { link = "FloatBorder" },
    BlinkCmpMenuSelection = { link = "PmenuSel" },
    BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
    BlinkCmpScrollBarGutter = { link = "PmenuSbar" },

    BlinkCmpLabel = { fg = palette.fg },
    BlinkCmpLabelMatch = { fg = palette.accent, bold = true },
    BlinkCmpLabelDetail = { fg = palette.secondary },
    BlinkCmpLabelDescription = { fg = palette.secondary },
    BlinkCmpKind = { fg = palette.secondary },
    BlinkCmpSource = { fg = palette.secondary },
    BlinkCmpGhostText = { fg = palette.comment },

    BlinkCmpDoc = { link = "NormalFloat" },
    BlinkCmpDocBorder = { link = "FloatBorder" },
    BlinkCmpDocSeparator = { link = "NormalFloat" },
    BlinkCmpDocCursorLine = { link = "Visual" },
    BlinkCmpSignatureHelp = { link = "NormalFloat" },
    BlinkCmpSignatureHelpBorder = { link = "NormalFloat" },
    BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },

    BlinkCmpKindText = { fg = palette.secondary },
    BlinkCmpKindMethod = { fg = palette.magenta },
    BlinkCmpKindFunction = { fg = palette.magenta },
    BlinkCmpKindConstructor = { fg = palette.orange },
    BlinkCmpKindField = { link = "@variable.member" },
    BlinkCmpKindVariable = { link = "@variable.member" },
    BlinkCmpKindClass = { link = "BlinkCmpKindConstructor" },
    BlinkCmpKindInterface = { fg = palette.blue5 },
    BlinkCmpKindModule = { link = "BlinkCmpKindClass" },
    BlinkCmpKindProperty = { link = "BlinkCmpKindField" },
    BlinkCmpKindUnit = { link = "BlinkCmpKindField" },
    BlinkCmpKindValue = { link = "@variable.member" },
    BlinkCmpKindEnum = { link = "BlinkCmpKindConstructor" },
    BlinkCmpKindKeyword = { fg = palette.yellow },
    BlinkCmpKindSnippet = { fg = palette.yellow },
    BlinkCmpKindColor = { link = "cssColor" },
    BlinkCmpKindFile = { link = "@text.uri" },
    BlinkCmpKindReference = { link = "@variable.parameter.reference" },
    BlinkCmpKindFolder = { link = "NeotestDir" },
    BlinkCmpKindEnumMember = { link = "@variable.member" },
    BlinkCmpKindConstant = { link = "@constant" },
    BlinkCmpKindStruct = { link = "@structure" },
    BlinkCmpKindEvent = { fg = palette.yellow },
    BlinkCmpKindOperator = { link = "@operator" },
    BlinkCmpKindTypeParameter = { link = "@variable.parameter" },
    BlinkCmpKindCopilot = { fg = palette.teal },
  }
end
